require: rubocop-rails

AllCops:
  Exclude:
    - '**/*.slim'
    - bin/*
    - config/initializers/*
    - db/schema.rb

  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable


Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Style/HashSyntax:
  Exclude:
    - 'app/views/**/*.slim'
