require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - '**/*.slim'
    - bin/*
    - db/schema.rb
  SuggestExtensions: false
  NewCops: enable


Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/initializers/simple_form_bootstrap.rb
    - lib/tasks/auto_annotate_models.rake

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Lint/RedundantCopDisableDirective:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
