default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # database: hexlet_education_postgres
  # username: hexlet_education_postgres_user
  # password: m43CdpJ0lvzbcWqccRevVNNoZxFdbLWR
  # host: dpg-cneuouev3ddc73adhr40-a
  # port: 5432
